micronaut:
  server:
    port: 8133
  application:
    name: aglGameService
  security:
    intercept-url-map:
      - pattern: /api/games
        http-method: GET
        access:
          - isAuthenticated()
      - pattern: /api/games/images
        http-method: GET
        access:
          - isAuthenticated()
      - pattern: /api/games/save
        http-method: POST
        access:
          - isAuthenticated()
      - pattern: /api/games/save/update
        http-method: PUT
        access:
          - isAuthenticated()
      - pattern: /api/games/search
        http-method: PUT
        access:
          - isAnonymous()
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
netty:
  default:
    allocator:
      max-order: 3
  http:
    client:
      read-timeout: 10s
      header:
        propagation:
          enabled: false

flyway:
  datasources:
    default:
      locations: classpath:/db/migration
      baseline-on-migrate: false
      validate-on-migrate: true


datasources:
  default:
    url: ${PG_JDBC_URL:`jdbc:postgresql://localhost:5432/usergameinfo`}
    username: ${PG_USERNAME:postgres}
    password: ${PG_PASSWORD:AstonVilla!96}
    driver-class-name: org.postgresql.Driver
    schema-generate: NONE
    dialect: POSTGRES

rawg-adapter:
  api:
    url: http://localhost:8132
