micronaut:
  application:
    name: aglGameService
netty:
  default:
    allocator:
      max-order: 3
  http:
    client:
      read-timeout: 10s
      header:
        propagation:
          enabled: false

flyway:
  datasources:
    default:
      locations: classpath:/db/migration
      baseline-on-migrate: false
      validate-on-migrate: true


datasources:
  default:
    url: ${PG_JDBC_URL:`jdbc:postgresql://10.101.42.239/usergameinfo`}
    username: ${PG_USERNAME:amsumner}
    password: ${PG_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    schema-generate: NONE
    dialect: POSTGRES

rawg-adapter:
  api:
    url: http://agl-rawg-adapter:80
